name: epicookbook

channels:
  - conda-forge

dependencies:
  - pip:
    - bs4
    - tqdm
    - numpy
    - pyyaml
    - nbformat
    - nbclean
    - scipy
    - pandas
    - matplotlib
    - plotly


